"""Add 'first_name', 'last_name' and 'avatar' columns

Revision ID: 8083cbf692db
Revises: 66ecbd93ed56
Create Date: 2021-09-02 19:50:03.309847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8083cbf692db'
down_revision = '66ecbd93ed56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'avatar')
    op.drop_column('accounts', 'last_name')
    op.drop_column('accounts', 'first_name')
    # ### end Alembic commands ###
